#GET  http://localhost:8080/api/agents/A12345

POST  http://localhost:8080/api/agents/create
{
  "matricule": "14e215",
  "nom": "KOUADIO",
  "prenom": "Franck",
  "dateNaissance": "1987-06-15",
  "indice": 2,
  "salaireBase": 1200,
  "allocationFamiliale": 150,
  "nbreEnfant": 3,
  "actif": true,
  "enfants": [
    {
      "nom": "KOUADIO",
      "prenom": "Adjoua",
      "dateNaissance": "2013-03-21"
    },
    {
      "nom": "KOUADIO",
      "prenom": "Koffi",
      "dateNaissance": "2016-09-10"
    },
    {
      "nom": "KOUADIO",
      "prenom": "Akissi",
      "dateNaissance": "2019-12-05"
    }
  ]
}



#PUT http://localhost:8080/api/agents/85552gg8855
#{
#  "nom": "Durand",
#  "prenom": "Jean",
#  "dateNaissance": "1990-05-10",
#  "indice": 200,
#  "salaireBase": 350000,
#  "allocationFamiliale": 25000,
#  "nbreEnfant": 2,
#  "actif": true
#}

